// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v4.25.3
// source: proto/emergencias.proto

package emergenciaspb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Emergencia struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Latitude      int32                  `protobuf:"varint,2,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude     int32                  `protobuf:"varint,3,opt,name=longitude,proto3" json:"longitude,omitempty"`
	Magnitude     int32                  `protobuf:"varint,4,opt,name=magnitude,proto3" json:"magnitude,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Emergencia) Reset() {
	*x = Emergencia{}
	mi := &file_proto_emergencias_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Emergencia) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Emergencia) ProtoMessage() {}

func (x *Emergencia) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Emergencia.ProtoReflect.Descriptor instead.
func (*Emergencia) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{0}
}

func (x *Emergencia) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Emergencia) GetLatitude() int32 {
	if x != nil {
		return x.Latitude
	}
	return 0
}

func (x *Emergencia) GetLongitude() int32 {
	if x != nil {
		return x.Longitude
	}
	return 0
}

func (x *Emergencia) GetMagnitude() int32 {
	if x != nil {
		return x.Magnitude
	}
	return 0
}

type EmergenciasRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Emergencias   []*Emergencia          `protobuf:"bytes,1,rep,name=emergencias,proto3" json:"emergencias,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EmergenciasRequest) Reset() {
	*x = EmergenciasRequest{}
	mi := &file_proto_emergencias_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EmergenciasRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EmergenciasRequest) ProtoMessage() {}

func (x *EmergenciasRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EmergenciasRequest.ProtoReflect.Descriptor instead.
func (*EmergenciasRequest) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{1}
}

func (x *EmergenciasRequest) GetEmergencias() []*Emergencia {
	if x != nil {
		return x.Emergencias
	}
	return nil
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_proto_emergencias_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{2}
}

type Actualizacion struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mensaje       string                 `protobuf:"bytes,1,opt,name=mensaje,proto3" json:"mensaje,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Actualizacion) Reset() {
	*x = Actualizacion{}
	mi := &file_proto_emergencias_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Actualizacion) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Actualizacion) ProtoMessage() {}

func (x *Actualizacion) ProtoReflect() protoreflect.Message {
	mi := &file_proto_emergencias_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Actualizacion.ProtoReflect.Descriptor instead.
func (*Actualizacion) Descriptor() ([]byte, []int) {
	return file_proto_emergencias_proto_rawDescGZIP(), []int{3}
}

func (x *Actualizacion) GetMensaje() string {
	if x != nil {
		return x.Mensaje
	}
	return ""
}

var File_proto_emergencias_proto protoreflect.FileDescriptor

const file_proto_emergencias_proto_rawDesc = "" +
	"\n" +
	"\x17proto/emergencias.proto\x12\vemergencias\"x\n" +
	"\n" +
	"Emergencia\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1a\n" +
	"\blatitude\x18\x02 \x01(\x05R\blatitude\x12\x1c\n" +
	"\tlongitude\x18\x03 \x01(\x05R\tlongitude\x12\x1c\n" +
	"\tmagnitude\x18\x04 \x01(\x05R\tmagnitude\"O\n" +
	"\x12EmergenciasRequest\x129\n" +
	"\vemergencias\x18\x01 \x03(\v2\x17.emergencias.EmergenciaR\vemergencias\"\a\n" +
	"\x05Empty\")\n" +
	"\rActualizacion\x12\x18\n" +
	"\amensaje\x18\x01 \x01(\tR\amensaje2^\n" +
	"\x12ServicioAsignacion\x12H\n" +
	"\x11EnviarEmergencias\x12\x1f.emergencias.EmergenciasRequest\x1a\x12.emergencias.Empty2R\n" +
	"\x0eServicioDrones\x12@\n" +
	"\x11AsignarEmergencia\x12\x17.emergencias.Emergencia\x1a\x12.emergencias.Empty2Z\n" +
	"\x11ServicioMonitoreo\x12E\n" +
	"\x13EnviarActualizacion\x12\x1a.emergencias.Actualizacion\x1a\x12.emergencias.EmptyB\x15Z\x13proto/emergenciaspbb\x06proto3"

var (
	file_proto_emergencias_proto_rawDescOnce sync.Once
	file_proto_emergencias_proto_rawDescData []byte
)

func file_proto_emergencias_proto_rawDescGZIP() []byte {
	file_proto_emergencias_proto_rawDescOnce.Do(func() {
		file_proto_emergencias_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_emergencias_proto_rawDesc), len(file_proto_emergencias_proto_rawDesc)))
	})
	return file_proto_emergencias_proto_rawDescData
}

var file_proto_emergencias_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_emergencias_proto_goTypes = []any{
	(*Emergencia)(nil),         // 0: emergencias.Emergencia
	(*EmergenciasRequest)(nil), // 1: emergencias.EmergenciasRequest
	(*Empty)(nil),              // 2: emergencias.Empty
	(*Actualizacion)(nil),      // 3: emergencias.Actualizacion
}
var file_proto_emergencias_proto_depIdxs = []int32{
	0, // 0: emergencias.EmergenciasRequest.emergencias:type_name -> emergencias.Emergencia
	1, // 1: emergencias.ServicioAsignacion.EnviarEmergencias:input_type -> emergencias.EmergenciasRequest
	0, // 2: emergencias.ServicioDrones.AsignarEmergencia:input_type -> emergencias.Emergencia
	3, // 3: emergencias.ServicioMonitoreo.EnviarActualizacion:input_type -> emergencias.Actualizacion
	2, // 4: emergencias.ServicioAsignacion.EnviarEmergencias:output_type -> emergencias.Empty
	2, // 5: emergencias.ServicioDrones.AsignarEmergencia:output_type -> emergencias.Empty
	2, // 6: emergencias.ServicioMonitoreo.EnviarActualizacion:output_type -> emergencias.Empty
	4, // [4:7] is the sub-list for method output_type
	1, // [1:4] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_proto_emergencias_proto_init() }
func file_proto_emergencias_proto_init() {
	if File_proto_emergencias_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_emergencias_proto_rawDesc), len(file_proto_emergencias_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   3,
		},
		GoTypes:           file_proto_emergencias_proto_goTypes,
		DependencyIndexes: file_proto_emergencias_proto_depIdxs,
		MessageInfos:      file_proto_emergencias_proto_msgTypes,
	}.Build()
	File_proto_emergencias_proto = out.File
	file_proto_emergencias_proto_goTypes = nil
	file_proto_emergencias_proto_depIdxs = nil
}
